### ISSUE TITLE
TypeError while loading from TemporaryFile (Python 3)

### ISSUE THREAD

**Issue by Codeman73** [python-intelhex/intelhex#37]
I tried to load an HEX-Image from a TemporaryFile() with python 3.

Unfortunately the behaviour of TemporaryFile() differ from a normal file object.
Whereas file object read 'str' type, a TemporaryFile() read and writes 'bytes' type.
You can see the conversion in the code snippet below.

```
fobj = open('testimage.hex','r')
data = fobj.read()

ftmp = TemporaryFile()
ftmp.write(bytes(data,encoding='UTF-8'))
ftmp.seek(0)

ih.loadfile(ftmp, 'hex')

fobj.close()
ftmp.close()
```

Executing the code throws following exception:
    decode(s, line)
  File "D:\Programme\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\lib\site-packages\intelhex\__init__.py", line 111, in _decode_record
    s = s.rstrip('\r\n')
TypeError: 'str' does not support the buffer interface

In ...\__init__.py", line 111, in _decode_record, I inserted
```
        if isinstance(s, bytes):
            s = s.decode()
        s = s.rstrip('\r\n')
```
before the s = s.rstrip('\r\n') to convert it to str.

Well, it solves my problem in python 3. I don't know if it is compatible with python 2.
What do you think? Is it applicable in future releases.

**Comment by r-downing** [comment]
TemporaryFile opens as binary by default

From the [docs](https://docs.python.org/3/library/tempfile.html):
tempfile.TemporaryFile(**mode='w+b'**, buffering=None, encoding=None, newline=None, suffix=None, prefix=None, dir=None, *, errors=None)

^ Note the **b**

Try changing it to
```
...
ftmp = TemporaryFile(mode="w+")
ftmp.write(data)
ftmp.seek(0)

ih.loadfile(ftmp, 'hex')
...
```

**Comment by bialix** [comment]
It seems no changes to IntelHex is needed.
