### ISSUE TITLE
The binary limitation of bin2hex is 4Kbytes.

### ISSUE THREAD

**Issue by lu-ym** [python-intelhex/intelhex#39]
Any binary file over 4K will only be transforms the first 4Kbytes. The rest are discard.

**Comment by lu-ym** [comment]
I think this may be introduced by windows system buffer. Is there any solution or workaround now?

**Comment by bialix** [comment]
There is no internal limitations in IntelHex library. Can you provide more info and example file?
Your OS version, Pytthon version, IntelHex library version.
Example of input and output file, how do you check result?

**Comment by lu-ym** [comment]
Sorry, my bad.  It is a usage error.  I transform a binary to hex while it is still opened by another program.
