### ISSUE TITLE
bin2hex.py adds extra random byte

### ISSUE THREAD

**Issue by odin-** [python-intelhex/intelhex#61]
I am using bin2hex.py:

bin2hex.py test out.ihex; cat out.ihex
:0200000061326B
:00000001FF

Note '0x6B'. 

Input is two chars in a binary file:

![image](https://user-images.githubusercontent.com/7396319/235608651-402ebcc0-a814-4fe1-88e5-0c50aaf75c58.png)

Is this expected behaviour?

**Comment by bialix** [comment]
The last byte is always checksum. See docs.

**Comment by odin-** [comment]
Oh thanks :-)
